name: Deploy to Production

on:
  push:
    branches: [main, develop]
  workflow_dispatch:  # This allows manual triggering!

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-to-s3.yml
    with:
      repo_name: cc-wrapper
    secrets: inherit

